on:
  push:
    branches:
      - main
    paths:
      - beanIndex-cli/**
  
  
  workflow_dispatch:

jobs:
  deployCli:
    defaults:
      run:
        shell: bash
        working-directory: ./beanIndex-cli
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          role-to-assume: ${{ vars.AWS_DEPLOY_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Get API URL
        run: |
          echo "API_IP=$(aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)" >> $GITHUB_ENV

      - name: Write google credential file
        run: ${{ secrets.GOOGLE_CLIENT }} > ./src/main/resources/client_secret.json

      - 
